### PR TITLE
Doc update

### PR DESCRIPTION
**Pull request by opoudjis**
This is my follow up PR, with updates from all other gems, and updates to ITU and to relaton integration.

### CODE REVIEW

**Comment by opoudjis** [comment]
@strogonoff This needs to be actioned, it is holding up other documentation updates, and I am already publishing gem updates which have eliminated their own documentation. Please provide an ETA.

**Comment by ronaldtse** [comment]
@strogonoff urgent need to merge this -- the READMEs in the gems have been removed. So there's no documentation except this one. Thanks.

**Comment by ronaldtse** [comment]
@strogonoff , can we merge this ASAP? Thanks!

**Comment by strogonoff** [comment]
@opoudjis thanks for the PR, let me take a look.

@ronaldtse, I’just finished a big update of Metanorma.com migrating it to latest theme version. I will now start merging this. Hopefully there won’t be a lot of merge headache, since not a lot of my changes affected documentation copy, though I did some work on it too.

**Comment by ronaldtse** [comment]
@strogonoff ping 😉

**Comment by opoudjis** [comment]
Given that a major restructure of the site is about to happen, and I have A MONTH'S WORTH OF UPDATES STILL PENDING that I have not been able to check in, this pull request is overdue. It is a priority that this be resolved.

**Comment by strogonoff** [comment]
@opoudjis can you look at this? https://github.com/metanorma/metanorma.com/pull/74#issuecomment-480653966

**Comment by opoudjis** [comment]
... So, I'm going to review all those edits (which I made), and confirm them? 

... Yes, these are all the changes I want.

**Comment by ronaldtse** [comment]
I believe @strogonoff wanted your review because it was rebased. 

Awesome — thanks guys!

**Comment by doktorgee** [comment]
Good news.

**Comment by opoudjis** [comment]
OK. Now comes the next checkin...

**Comment by strogonoff** [comment]
@ronaldtse @opoudjis 

Nick, but why did you make the same edits after I have specifically reverted them previously?

**Comment by ronaldtse** [comment]
@strogonoff probably a case of conflict resolution... if you don't mind could you help make a new PR to get back the lost changes? Thanks 😅

**Comment by opoudjis** [comment]
> Nick, but why did you make the same edits after I have specifically reverted them previously?

... I did?

**Pull request merged**
