### PR TITLE
Update markup to support responsive behavior in some images

### PR DESCRIPTION
**Pull request by manuel489**
Hi @ronaldtse,

Currently, there are many images in Metanorma website that are not responsive to the screen size (which is my fault).
This PR solves that (among other minor typos).

Thanks!

### CODE REVIEW

**Comment by strogonoff** [comment]
Actually, this may be an omission in open project styling.

For now I introduced a style override in https://github.com/metanorma/metanorma.com/commit/e434a2a692e98e94050d8c7080615bd1172e9666 that limits max width of images in page body to 100% on Metanorma.com, which should no longer require the attribute to be provided in AsciiDoc.

**Comment by strogonoff** [comment]
Since setting images to 100% in AsciiDoc markup should no longer be required, this PR could probably be closed without merging. I will close it when abovementioned styling changes are live (seems like there is a build failure to be addressed first). Thank you @manuel489 for bringing this issue to attention.

**Comment by strogonoff** [comment]
Fixed: https://www.metanorma.com/author/topics/document-format/section-terms/

**Comment by strogonoff** [comment]
@manuel489 I noticed that this PR contains other changes besides image widths. Some changes seem to fix AsciiDoc syntax errors, could you resubmit those changes?

**Comment by manuel489** [comment]
Thank you @strogonoff.
No problem, I'll resubmit the adoc markup changes in another PR  👍

**Pull request closed without merging**
