### PR TITLE
table markup: closes https://github.com/metanorma/metanorma-itu/issue…

### PR DESCRIPTION
**Pull request by opoudjis**
…s/85

### CODE REVIEW

**Comment by ronaldtse** [comment]
@anermina @opoudjis can you confirm this is accurate? If so, please help merge. Thanks.

**Comment by opoudjis** [comment]
So you're having the header cell centering override the column? Ugh, let me confirm that works...

**Comment by opoudjis** [comment]
It works, but my God, it looks disgusting in HTML, where tables are 100% width. Still, it illustrates a point. Accepting.

**Comment by ronaldtse** [comment]
Well clearly this solution burdens the authors, the general solution is to tag the value and text columns, but that’s not how it works now...

**Pull request merged**
