### PR TITLE
[WIP] Update chocolatey installation steps

### PR DESCRIPTION
**Pull request by CAMOBAP795**
Lets wait for https://chocolatey.org/packages/metanorma/1.1.4 approvement first

### CODE REVIEW

**Comment by strogonoff** [comment]
@ronaldtse does this mean we don’t get to the simplicity of `choco install metanorma` at this stage?

**Comment by ronaldtse** [comment]
@strogonoff yes.

1. Need to install Chocolatey
2. Need to install MSys2 via Chocolatey
3. The simplicity of `choco install metanorma -y`. (If you omit the `-y`, as with any other Chocolatey package, you will be hit by hundreds of "Y/N" prompts).

**Comment by strogonoff** [comment]
@ronaldtse understood, I will suggest to link to package manager’s docs for Chocolatey’s own installation and I see the MSys2 thing is unavoidable

**Comment by ronaldtse** [comment]
@strogonoff We used to link to Chocolatey for installation, but I noticed people "copy and pasting" the whole block without going to first install Chocolatey. So maybe we can split the steps and make it very clear what needs to be done.

**Comment by strogonoff** [comment]
What if someone already has Chocolatey, and copy-pastes the block that includes its installation? If it works without negative side-effects in that case, I have no objections.

**Comment by ronaldtse** [comment]
I think there won't be side effects (I tried that sometime ago), but you're right it is probably better to split this into two parts. As long as we make that clear I'm good.

**Comment by strogonoff** [comment]
By the way the reason I suggest to _link_ to package manager instruction docs is because they may change, if we copy the commands we may not keep up with the latest recommended way

**Comment by ronaldtse** [comment]
I honestly think:
- these steps shouldn’t be in a blog post (we should keep it in installation steps)
- and we need to update this section whenever chocolatey installation steps are changed.

**Comment by strogonoff** [comment]
OK let's go with your judgment!

**Comment by CAMOBAP795** [comment]
@ronaldtse I think we can merge it, let me know if you have some questions

**Comment by ronaldtse** [comment]
Agree. Thanks!

**Pull request merged**
