### PR TITLE
Remove wrong tip

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/metanorma.com/issues/92

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
@ronaldtse, unfortunately, this will not work, more info here https://github.com/metanorma/metanorma.com/issues/92#issuecomment-494915946

**Comment by CAMOBAP795** [comment]
@ronaldtse make sense? (comment above)

**Comment by ronaldtse** [comment]
So we just remove it? https://github.com/riboseinc/chocolatey-metanorma/pull/16 didn't help us with anything?

**Comment by CAMOBAP795** [comment]
@ronaldtse just rechecked, it helped partially, I will update PR in couple minutes

**Comment by CAMOBAP795** [comment]
@ronaldtse done

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !

**Pull request merged**
