### PR TITLE
Update yaml2text documentation (blog post and yaml2text documentation)

### PR DESCRIPTION
**Pull request by w00lf**
metanorma/metanorma-standoc#327, #331 documentation for yaml2text liquid support. @opoudjis @ronaldtse i have mentioned metnorma-standoc new version as 1.5.3, fell free to change it for the actual one after the release.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@w00lf The examples inside the page haven't been updated to Liquid yet. Can you please help update them too? e.g.

image

Thanks!

**Comment by w00lf** [comment]
> @w00lf The examples inside the page haven't been updated to Liquid yet. Can you please help update them too? e.g.
> 
> image
> 
> Thanks!

Done, added

**Comment by ronaldtse** [comment]
@w00lf thanks, but we still have the remaining examples in `yaml_to_text.adoc` file that use the old syntax. Can you help convert all of those to the new syntax? Thanks!

**Comment by w00lf** [comment]
> @w00lf thanks, but we still have the remaining examples in `yaml_to_text.adoc` file that use the old syntax. Can you help convert all of those to the new syntax? Thanks!



> yaml_to_text.adoc

I need to convert all old examples to liquid?

**Comment by ronaldtse** [comment]
Yes we want to drop the old syntax, so we want to convert all the examples.

**Comment by w00lf** [comment]
> Yes we want to drop the old syntax, so we want to convert all the examples.

Should i only leave block defining syntax, e.g. `[yaml2text,strings.yaml,arr]` and omit all other features? E.g. instead of using `{arr.*,item,EOS}` for iteration we now will use liquid iteration syntax, should we drop support for `*.#` special characters from docs?

**Comment by ronaldtse** [comment]
> Should i only leave block defining syntax, e.g. [yaml2text,strings.yaml,arr] and omit all other features? E.g. instead of using {arr.*,item,EOS} for iteration we now will use liquid iteration syntax, should we drop support for *.# special characters from docs?

I think we should drop support for `*.#` also because it can be done using Liquid with filter `xxx | size`.

**Comment by w00lf** [comment]
> > Should i only leave block defining syntax, e.g. [yaml2text,strings.yaml,arr] and omit all other features? E.g. instead of using {arr.*,item,EOS} for iteration we now will use liquid iteration syntax, should we drop support for *.# special characters from docs?
> 
> I think we should drop support for `*.#` also because it can be done using Liquid with filter `xxx | size`.

@ronaldtse updated all examples to use liquid syntax instead, gave refs to the official docs.

**Comment by ronaldtse** [comment]
Thanks @w00lf !

**Pull request merged**
